function getRandomWordSet() {
    const randomIndex = Math.floor(Math.random() * tabooWords.length);
    return tabooWords[randomIndex];
}

var tabooWords = [
    ["Aparat", ["Zdjęcie", "Obiektyw", "Fotografia", "Przycisk", "Błysk"]],     //*********************** A ***********************
    ["Alkohol", ["Piwo", "Wino", "Wódka", "Szklanka", "Trunek"]],
    ["Akcja", ["Film", "Bohater", "Dramat", "Scenariusz", "Reżyser"]],
    ["Amfiteatr", ["Scena", "Publiczność", "Spektakl", "Budowla", "Antyczny"]],
    ["Astronauta", ["Kosmos", "Rakieta", "Nasa", "Przestrzeń", "Kombinezon"]],
    ["Artysta", ["Obraz", "Scena", "Talent", "Sztuka", "Twórczość"]],
    ["Atom", ["Elektron", "Proton", "Neutron", "Fizyka", "Cząstka"]],
    ["Arbuz", ["Owoc", "Lato", "Zielony", "Nasiona", "Słodki"]],
    ["Akwarium", ["Ryba", "Woda", "Szklane", "Rośliny", "Podwodny"]],
    ["Apteka", ["Lekarz", "Lek", "Zdrowie", "Choroba", "Farmaceuta"]],
    ["Ameryka", ["Kontynent", "USA", "Stany", "Nowy Świat", "Prezydent"]],
    ["Ananas", ["Owoc", "Tropikalny", "Szypułki", "Ostry", "Słodki"]],
    ["Archeologia", ["Historia", "Wykopaliska", "Starożytność", "Artefakty", "Badania"]],
    ["Architektura", ["Budowla", "Projekt", "Budynek", "Styl", "Konstrukcja"]],
    ["Armatka", ["Broń", "Strzał", "Proch", "Kula", "Stare"]],
    ["Atmosfera", ["Powietrze", "Ziemia", "Ozon", "Warstwa", "Tlen"]],
    ["Atak", ["Walka", "Zbrodnia", "Obrona", "Wojna", "Agresja"]],
    ["Alergia", ["Kichanie", "Czerwony", "Reakcja", "Pyłek", "Leki"]],
    ["Atlas", ["Mapa", "Świat", "Geografia", "Książka", "Państwa"]],
    ["Autobus", ["Pojazd", "Przystanek", "Bilet", "Pasażerowie", "Kierowca"]],
    ["Algebra", ["Matematyka", "Równanie", "Liczby", "Nauka", "Zadanie"]],
    ["Akwatlon", ["Sport", "Bieganie", "Pływanie", "Zawody", "Dystans"]],
    ["Album", ["Zdjęcia", "Muzyka", "Płyta", "Strony", "Kolekcja"]],
    ["Aleja", ["Drzewa", "Droga", "Spacer", "Park", "Natura"]],
    ["Aktor", ["Teatr", "Film", "Rola", "Scena", "Sztuka"]],
    ["Antena", ["Sygnał", "Telewizja", "Radio", "Falownik", "Odbiornik"]],
    ["Ankieta", ["Pytania", "Badanie", "Odpowiedzi", "Dane", "Statystyki"]],
    ["Aspiryna", ["Lek", "Ból", "Głowa", "Tabletka", "Apteka"]],
    ["Akcent", ["Mowa", "Dźwięk", "Język", "Głoska", "Dialekt"]],
    ["Akademia", ["Nauka", "Uczelnia", "Student", "Kurs", "Wykładowca"]],
    ["Antybiotyk", ["Lek", "Choroba", "Bakterie", "Zdrowie", "Leczenie"]],
    ["Akcjonariusz", ["Spółka", "Akcje", "Inwestor", "Zysk", "Giełda"]],
    ["Artysta", ["Malować", "Twórczość", "Obraz", "Sztuka", "Inspiracja"]],
    ["Atleta", ["Sport", "Zawody", "Trening", "Siła", "Szybkość"]],
    ["Amulet", ["Talisman", "Szczęście", "Magia", "Ochrona", "Znaczek"]],
    ["Automat", ["Maszyna", "Monety", "Mechanizm", "Automatyczny", "Przycisk"]],
    ["Ałtaj", ["Góry", "Rosja", "Kraj", "Szczycie", "Wysokość"]],
    ["Aborygen", ["Tubylec", "Australia", "Ludzie", "Plemię", "Kultura"]],
    ["Amortyzator", ["Samochód", "Zawieszenie", "Sprężyna", "Jazda", "Drgania"]],
    ["Ankora", ["Kot", "Rasa", "Sierść", "Zwierzę", "Domowe"]],
    ["Antarktyda", ["Kontynent", "Lód", "Zimno", "Pingwiny", "Biegun"]],
    ["Akord", ["Muzyka", "Gitara", "Dźwięk", "Nota", "Melodia"]],
    ["Aerobik", ["Ćwiczenia", "Fitness", "Zdrowie", "Ruch", "Gimnastyka"]],
    ["Awanse", ["Praca", "Promocja", "Zasługa", "Zawód", "Pozycja"]],
    ["Astma", ["Oddychanie", "Choroba", "Płuca", "Dusznosć", "Inhalator"]],
    ["Asceza", ["Wyrzeczenia", "Duchowość", "Medytacja", "Skromność", "Świętość"]],
    ["Adrenalina", ["Hormon", "Stres", "Emocje", "Ciało", "Ekscytacja"]],
    ["Arystokracja", ["Klasa", "Bogaci", "Szlachta", "Władza", "Ziemia"]],
    ["Aerodynamika", ["Fizyka", "Ruch", "Powietrze", "Prędkość", "Odporność"]],
    ["Atrakcja", ["Rozrywka", "Park", "Zabawa", "Widowisko", "Zainteresowanie"]],
    ["Abecadło", ["Alfabet", "Litera", "Nauka", "Dzieci", "Czytanie"]],
    ["Analogia", ["Podobieństwo", "Porównanie", "Relacja", "Łączność", "Logiczny"]],
    ["Arbitraż", ["Decyzja", "Rozstrzygnięcie", "Sędzia", "Spór", "Równowaga"]],
    ["Akustyczny", ["Dźwięk", "Muzyka", "Słuch", "Fala", "Instrument"]],
    ["Ambasada", ["Kraj", "Dyplomacja", "Ambasador", "Zagranica", "Reprezentacja"]],
    ["Alergen", ["Alergia", "Reakcja", "Ciało", "Sensibilizacja", "Produkt"]],
    ["Autonomia", ["Niepodległość", "Samodzielność", "Władza", "Terytorium", "Prawo"]],
    ["Azyl", ["Schronienie", "Bezpieczeństwo", "Uchodźca", "Pomoc", "Prawo"]],
    ["Altruizm", ["Dobroć", "Bezinteresowność", "Pomoc", "Dobro", "Charakter"]],
    ["Astrologia", ["Gwiazdy", "Horoskop", "Znak zodiaku", "Przyszłość", "Wróżba"]],
    ["Antykwariat", ["Książki", "Stary", "Wartość", "Zbieranie", "Literatura"]],
    ["Antropologia", ["Nauka", "Człowiek", "Kultura", "Społeczeństwo", "Ewolucja"]],
    ["Amortyzacja", ["Zużycie", "Wartość", "Sprzęt", "Finanse", "Ekonomia"]],
    ["Asymetria", ["Geometria", "Różnica", "Forma", "Zakrzywienie", "Nierówność"]],
    ["Adopcja", ["Rodzina", "Dziecko", "Sąd", "Opieka", "Rodzice"]],
    ["Arbiter", ["Sędzia", "Decyzja", "Mecz", "Sport", "Reguły"]],
    ["Audycja", ["Radio", "Nagranie", "Muzyka", "Głos", "Mikrofon"]],
    ["Alpinizm", ["Wspinaczka", "Góry", "Sport", "Ryzyko", "Lina"]],
    ["Archebakterie", ["Mikroorganizm", "Bakteria", "Życie", "Organizm", "Biologia"]],
    ["Amfibia", ["Zwierzę", "Woda", "Ląd", "Żaba", "Życie"]],
    ["Anatomia", ["Ciało", "Nauka", "Organ", "Medycyna", "Struktura"]],
    ["Audytorium", ["Publiczność", "Widownia", "Wykład", "Miejsce", "Spotkanie"]],
    ["Awiator", ["Pilot", "Samolot", "Lot", "Powietrze", "Kabina"]],
    ["Ankora", ["Kot", "Rasa", "Sierść", "Turcja", "Zwierzę"]],
    ["Artysta", ["Sztuka", "Twórczość", "Malować", "Talent", "Inspiracja"]],
    ["Afera", ["Skandal", "Polityka", "Zasady", "Korupcja", "Wiadomości"]],
    ["Awangarda", ["Sztuka", "Innowacja", "Pionierski", "Styl", "Rewolucja"]],
    ["Amplituda", ["Fala", "Zasięg", "Ruch", "Dźwięk", "Wysokość"]],
    ["Autograf", ["Podpis", "Sława", "Gwiazda", "Fan", "Dowód"]],
    ["Auta", ["Pojazd", "Samochód", "Jazda", "Kierowca", "Ruch"]],
    ["Aorta", ["Serce", "Krew", "Tętnica", "Ciało", "Cyrkulacja"]],
    ["Asfalt", ["Droga", "Ulica", "Beton", "Budowa", "Samochód"]],
    ["Artysta", ["Sztuka", "Twórczość", "Obraz", "Wystawa", "Talent"]],
    ["Akwarela", ["Malarstwo", "Farba", "Sztuka", "Obraz", "Pędzel"]],
    ["Arbuz", ["Owoc", "Lato", "Zielony", "Woda", "Słodki"]],
    ["Aparat", ["Zdjęcie", "Obiektyw", "Fotografia", "Kamera", "Obraz"]],
    ["Analiza", ["Badanie", "Dane", "Nauka", "Metoda", "Ocena"]],
    ["Adrenalina", ["Hormon", "Emocje", "Stres", "Ciało", "Ekscytacja"]],
    ["Azyl", ["Schronienie", "Uchodźca", "Bezpieczeństwo", "Pomoc", "Prawo"]],
    ["Aromat", ["Zapach", "Smak", "Przyprawa", "Kuchnia", "Nosa"]],
    ["Abstrakcja", ["Sztuka", "Idea", "Obraz", "Rzeczywistość", "Wyobraźnia"]],
    ["Akcelerator", ["Prędkość", "Samochód", "Fizyka", "Cząstka", "Nauka"]],
    ["Ambasador", ["Dyplomacja", "Kraj", "Zagranica", "Rząd", "Reprezentacja"]],
    ["Agregat", ["Maszyna", "Narzędzie", "Budowa", "Ziemia", "Rola"]],
    ["Adiunkt", ["Nauka", "Uniwersytet", "Wykład", "Nauczyciel", "Stopień"]],
    ["Aktywista", ["Polityka", "Protest", "Społeczeństwo", "Ruch", "Przemiana"]],
    ["Animacja", ["Film", "Rysunek", "Kreskówka", "Komputer", "Tworzenie"]],
    ["Antropoid", ["Małpa", "Zwierzę", "Ewolucja", "Człowiek", "Nauka"]],
    ["Aglomeracja", ["Miasto", "Ludność", "Obszar", "Zabudowa", "Metropolia"]],
    ["Apartheid", ["Rasizm", "Prawo", "Segregacja", "Południowa Afryka", "Historia"]],
    ["Akustyka", ["Dźwięk", "Fala", "Muzyka", "Słuch", "Nauka"]],
    ["Atmosfera", ["Ziemia", "Powietrze", "Klimat", "Ochrona", "Warstwa"]],
    ["Arka", ["Statek", "Noe", "Biblia", "Zwierzęta", "Powódź"]],
    ["Amplituda", ["Fala", "Dźwięk", "Nauka", "Cykl", "Zakres"]],
    ["Akupunktura", ["Medycyna", "Igła", "Terapia", "Zdrowie", "Ciało"]],
    ["Atletyka", ["Sport", "Bieg", "Skok", "Stadion", "Mistrzostwa"]],
    ["Abstynencja", ["Alkohol", "Wstrzemięźliwość", "Zdrowie", "Decyzja", "Trzeźwość"]],
    ["Arystokracja", ["Klasa", "Społeczeństwo", "Bogaty", "Rządy", "Historia"]],
    ["Awokado", ["Owoc", "Zdrowie", "Dieta", "Zielony", "Jedzenie"]],
    ["Amalgamat", ["Dentysta", "Ząb", "Wypełnienie", "Srebro", "Zdrowie"]],
    ["Arkaizm", ["Słowo", "Stary", "Język", "Historia", "Używać"]],
    ["Akrobatyka", ["Gimnastyka", "Ruch", "Ciało", "Artysta", "Cyrk"]],
    ["Aluzja", ["Sugerować", "Podpowiedź", "Zrozumieć", "Komunikacja", "Myśl"]],
    ["Aklimatyzacja", ["Adaptacja", "Klimat", "Zmiana", "Ciało", "Zdrowie"]],
    ["Apostoł", ["Biblia", "Chrystus", "Religia", "Misja", "Wiara"]],
    ["Antagonista", ["Przeciwnik", "Konflikt", "Opowieść", "Bohater", "Literatura"]],
    ["Apteka", ["Leki", "Zdrowie", "Farmaceuta", "Choroba", "Sklep"]],

    ["Balon", ["Latać", "Powietrze", "Heł", "Kolor", "Festiwal"]],                      //****************** B **********************
    ["Bateria", ["Energia", "Elektryczność", "Ładować", "Telefon", "Prąd"]],
    ["Biologia", ["Nauka", "Życie", "Organizm", "Zdrowie", "Studia"]],
    ["Basen", ["Woda", "Pływanie", "Nurkowanie", "Ruch", "Cwiczenie"]],
    ["Budynek", ["Architektura", "Konstrukcja", "Mieszkanie", "Drzwi", "Okno"]],
    ["Bank", ["Pieniądze", "Konto", "Transakcja", "Kredyt", "Dewizy"]],
    ["Butelka", ["Napój", "Szklany", "Zamknięcie", "Wino", "Woda"]],
    ["Biblioteka", ["Książka", "Czytanie", "Wypożyczyć", "Wiedza", "Studia"]],
    ["Banana", ["Owoc", "Żółty", "Deser", "Sałatka", "Smoothie"]],
    ["Babcia", ["Rodzina", "Stary", "Dzieci", "Miłość", "Rodzice"]],
    ["Biurko", ["Praca", "Meble", "Studia", "Komputer", "Pisanie"]],
    ["Brzoza", ["Drzewo", "Liść", "Natura", "Las", "Biały"]],
    ["Bieganie", ["Sport", "Ruch", "Zdrowie", "Szybkość", "Maraton"]],
    ["Buldog", ["Pies", "Rasa", "Zwierzę", "Dom", "Anglia"]],
    ["Bilet", ["Podróż", "Cena", "Pociąg", "Samolot", "Kino"]],
    ["Bukiet", ["Kwiaty", "Prezent", "Miłość", "Róże", "Ślub"]],
    ["Błyskawica", ["Pogoda", "Burza", "Elektryczność", "Niebo", "Deszcz"]],
    ["Brama", ["Wejście", "Drzwi", "Otwarcie", "Zamknięcie", "Klucz"]],
    ["Bakteria", ["Mikroorganizm", "Choroba", "Zdrowie", "Nauka", "Ciało"]],
    ["Beczka", ["Pojemnik", "Wino", "Piwo", "Drewno", "Przechowywanie"]],
    ["Bezpieczeństwo", ["Ochrona", "Zasady", "Policja", "Zagrożenie", "Zdrowie"]],
    ["Bocian", ["Ptak", "Lato", "Lot", "Gniazdo", "Dzieci"]],
    ["Bumerang", ["Rzut", "Powrót", "Australia", "Gra", "Drewno"]],
    ["Bibliografia", ["Książka", "Cytat", "Autor", "Nauka", "Praca"]],
    ["Bambus", ["Roślina", "Azja", "Drzewo", "Zielony", "Meble"]],
    ["Bukiet", ["Kwiaty", "Róże", "Dary", "Miłość", "Ślub"]],
    ["Bajka", ["Opowieść", "Dzieci", "Moralność", "Postać", "Czarodziejka"]],
    ["Białko", ["Jedzenie", "Mięso", "Zdrowie", "Dieta", "Sport"]],
    ["Bezdomność", ["Ulica", "Brak domu", "Bieda", "Problem społeczny", "Życie"]],
    ["Bursztyn", ["Kamień", "Biżuteria", "Bałtyk", "Żółty", "Prehistoryczny"]],
    ["Brud", ["Czystość", "Myć", "Zanieczyszczenie", "Śmieci", "Grunt"]],
    ["Burza", ["Pogoda", "Deszcz", "Piorun", "Chmury", "Wiatr"]],
    ["Biegunka", ["Choroba", "Jedzenie", "Zdrowie", "Ciało", "Lek"]],
    ["Brzeg", ["Morze", "Rzeka", "Woda", "Piasek", "Wybrzeże"]],
    ["Baryłka", ["Pojemnik", "Wino", "Ropa", "Drewno", "Przechowywanie"]],
    ["Bezprzewodowy", ["Technologia", "Wifi", "Internet", "Komputer", "Telefon"]],
    ["Buzia", ["Twarz", "Usta", "Uśmiech", "Pocałunek", "Dzieci"]],
    ["Balustrada", ["Schody", "Bezpieczeństwo", "Architektura", "Poręcz", "Balkon"]],
    ["Bryłka", ["Kształt", "Lód", "Cukier", "Kawałek", "Mały"]],
    ["Bandaż", ["Zdrowie", "Rana", "Opaska", "Lekarz", "Pierwsza pomoc"]],
    ["Biathlon", ["Sport", "Narty", "Strzelanie", "Zima", "Wyścig"]],
    ["Bezrobocie", ["Praca", "Pieniądze", "Ekonomia", "Zatrudnienie", "Rząd"]],
    ["Bilard", ["Gra", "Stół", "Kule", "Kij", "Zasady"]],
    ["Bliźnięta", ["Rodzeństwo", "Podobieństwo", "Rodzina", "Urodzenie", "Geny"]],
    ["Bocznica", ["Kolej", "Pociąg", "Tory", "Stacja", "Transport"]],
    ["Bard", ["Poeta", "Śpiew", "Piosenka", "Muzyka", "Historia"]],
    ["Beton", ["Budowa", "Materiał", "Cement", "Konstrukcja", "Mocny"]],
    ["Bonsai", ["Drzewo", "Japonia", "Roślina", "Sztuka", "Mały"]],
    ["Bungalow", ["Dom", "Jednopoziomowy", "Mieszkanie", "Budynek", "Architektura"]],
    ["Biskup", ["Kościół", "Religia", "Katolicki", "Władza", "Suknia"]],
    ["Bronz", ["Metal", "Statua", "Rzeźba", "Stary", "Muzeum"]],
    ["Bumerang", ["Australia", "Rzut", "Powrót", "Gra", "Drewno"]],
    ["Barok", ["Sztuka", "Styl", "Historia", "Muzyka", "Architektura"]],
    ["Brzemię", ["Ciężar", "Problem", "Stres", "Odpowiedzialność", "Naprzód"]],
    ["Buczek", ["Wiadro", "Woda", "Pojemnik", "Metal", "Nosić"]],
    ["Bazylia", ["Zioło", "Jedzenie", "Smak", "Kuchnia", "Pesto"]],
    ["Burak", ["Warzywo", "Czerwony", "Jedzenie", "Zdrowie", "Surowy"]],
    ["Błazen", ["Klaun", "Śmiech", "Komedia", "Cyrk", "Zabawa"]],
    ["Bractwo", ["Organizacja", "Związek", "Członkostwo", "Grupa", "Wsparcie"]],
    ["Bibliofil", ["Książka", "Czytanie", "Miłość", "Zbieranie", "Wiedza"]],
    ["Bogactwo", ["Pieniądze", "Bogaty", "Zamożność", "Sukces", "Luksus"]],
    ["Bzdura", ["Nieprawda", "Kłamstwo", "Fałsz", "Mówić", "Głupota"]],
    ["Bujak", ["Zabawa", "Dzieci", "Plac zabaw", "Huśtawka", "Ruch"]],
    ["Bluszcz", ["Roślina", "Zielony", "Ogrodnictwo", "Wspinaczka", "Liście"]],
    ["Butan", ["Gaz", "Palny", "Chemia", "Zapalniczka", "Ciepło"]],
    ["Biwak", ["Kemping", "Noc", "Namiot", "Przyroda", "Ogień"]],
    ["Bukmacher", ["Zakłady", "Pieniądze", "Sport", "Ryzyko", "Gra"]],
    ["Baśń", ["Opowieść", "Dzieci", "Moralność", "Postać", "Czarodziejka"]],
    ["Blenda", ["Fotografia", "Światło", "Refleks", "Obraz", "Zdjęcie"]],
    ["Bractwo", ["Organizacja", "Związek", "Członkostwo", "Grupa", "Wsparcie"]],
    ["Balans", ["Równowaga", "Stabilność", "Równość", "Waga", "Stabilizacja"]],
    ["Bajer", ["Kłamstwo", "Opowieść", "Zmyślenie", "Nieprawda", "Fałszywy"]],
    ["Brzeg", ["Rzeka", "Morze", "Woda", "Piasek", "Wybrzeże"]],
    ["Bałwan", ["Śnieg", "Zima", "Budowa", "Dzieci", "Marchewka"]],
    ["Bukiet", ["Kwiaty", "Prezent", "Róże", "Ślub", "Uroczystość"]],
    ["Bieganie", ["Sport", "Wytrzymałość", "Maraton", "Buty", "Szybkość"]],
    ["Bakteria", ["Mikroby", "Choroba", "Mikroskop", "Zdrowie", "Antybiotyk"]],
    ["Basen", ["Woda", "Pływanie", "Ratownik", "Kąpiel", "Okulary"]],
    ["Balerina", ["Taniec", "Balet", "Scena", "Spódnica", "Piruet"]],
    ["Beczka", ["Drewno", "Pojemnik", "Wino", "Płyn", "Kran"]],
    ["Brydż", ["Karty", "Gra", "Zasady", "Punktacja", "Czwórka"]],
    ["Błyskawica", ["Piorun", "Burza", "Elektryczność", "Niebo", "Załamanie pogody"]],
    ["Baza", ["Podstawa", "Ośrodek", "Miejsce", "Lokalizacja", "Zasoby"]],
    ["Badanie", ["Test", "Nauka", "Lekarz", "Eksperyment", "Analiza"]],
    ["Broń", ["Pistolet", "Strzał", "Nabój", "Wojna", "Obronność"]],
    ["Bieżnia", ["Bieganie", "Sport", "Trenażer", "Trening", "Prędkość"]],
    ["Buzia", ["Twarz", "Usta", "Uśmiech", "Dziecko", "Całus"]],
    ["Bitwa", ["Wojna", "Walka", "Zwycięstwo", "Przegrana", "Armia"]],
    ["Bicz", ["Chłosta", "Karanie", "Uderzenie", "Pain", "Skóra"]],
    ["Błąd", ["Pomyłka", "Problem", "Niewłaściwy", "Poprawka", "Zgubić"]],
    ["Betoniarz", ["Budowa", "Praca", "Beton", "Mieszać", "Konstrukcja"]],
    ["Biedronka", ["Insekt", "Czerwony", "Kropki", "Owad", "Lot"]],
    ["Bożonarodzeniowy", ["Święta", "Prezent", "Drzewo", "Śnieg", "Dekoracje"]],
    ["Brak", ["Nieobecność", "Niedostatek", "Zagubiony", "Zniknięcie", "Pusty"]],
    ["Bęben", ["Perkusja", "Muzyka", "Rytm", "Pałeczki", "Dźwięk"]],
    ["Bumerang", ["Australia", "Rzut", "Powrót", "Gra", "Drewno"]],
    ["Bąbel", ["Woda", "Pęcherz", "Skóra", "Ból", "Pęknięcie"]],
    ["Bomba", ["Eksplozja", "Wybuch", "Zniszczenie", "Terrorysta", "Niebezpieczny"]],
    ["Babeczka", ["Ciasto", "Słodki", "Pieczenie", "Cukier", "Deser"]],
    ["Bryza", ["Wiatr", "Morze", "Powiew", "Żagiel", "Chłodzenie"]],

    ["Czajnik", ["Herbata", "Woda", "Gorący", "Kuchnia", "Elektryczny"]],                   //******************  C  ************************ */
    ["Cegła", ["Budowa", "Mur", "Dom", "Czerwony", "Zaprawa"]],
    ["Czekolada", ["Słodki", "Deser", "Kakao", "Tabliczka", "Mleko"]],
    ["Cytryna", ["Owoc", "Kwaśny", "Żółty", "Limonka", "Sok"]],
    ["Czas", ["Zegar", "Godzina", "Minuta", "Sekunda", "Przyszłość"]],
    ["Człowiek", ["Osoba", "Ciało", "Życie", "Myślenie", "Emocje"]],
    ["Czytanie", ["Książka", "Tekst", "Lektura", "Zrozumienie", "Strona"]],
    ["Czerwień", ["Kolor", "Róż", "Żółty", "Zielony", "Niebieski"]],
    ["Chleb", ["Jedzenie", "Pieczywo", "Zboże", "Piekarz", "Masło"]],
    ["Cicha noc", ["Kolęda", "Święta", "Muzyka", "Noc", "Spokój"]],
    ["Cztery pory roku", ["Zima", "Wiosna", "Lato", "Jesień", "Kalendarz"]],
    ["Cukrzyca", ["Choroba", "Insulina", "Cukier", "Dieta", "Leczenie"]],
    ["Czołg", ["Wojna", "Armia", "Broni", "Pancerz", "Bitwa"]],
    ["Cymbał", ["Instrument", "Muzyka", "Dźwięk", "Perkusja", "Orkiestra"]],
    ["Czarownica", ["Magia", "Czar", "Miotełka", "Halloween", "Baśń"]],
    ["Cekiny", ["Błysk", "Moda", "Sukienka", "Ozdoba", "Świetlista"]],
    ["Czeladź", ["Miasto", "Polska", "Zabrze", "Śląsk", "Zamieszkały"]],
    ["Cyganeria", ["Bohema", "Artysta", "Kultura", "Życie", "Wolność"]],
    ["Cebula", ["Warzywo", "Gotowanie", "Smak", "Zupa", "Sałatka"]],
    ["Cieniowanie", ["Rysunek", "Artysta", "Ołówek", "Światło", "Ciemność"]],
    ["Czarna dziura", ["Kosmos", "Grawitacja", "Galaktyka", "Nauka", "Gwiazda"]],
    ["Czujnik", ["Elektronika", "Dane", "Technologia", "Pomiar", "Urządzenie"]],
    ["Cukierek", ["Słodki", "Dzieci", "Deser", "Cukier", "Smak"]],
    ["Czarna owca", ["Inny", "Rodzina", "Wyjątek", "Niepasujący", "Idiom"]],
    ["Chmury", ["Niebo", "Pogoda", "Deszcz", "Biały", "Zachmurzony"]],
    ["Cukinia", ["Warzywo", "Zielony", "Jedzenie", "Gotowanie", "Grill"]],
    ["Czeluść", ["Otwór", "Jaskinia", "Głębia", "Mroczny", "Przepaść"]],
    ["Czoło", ["Twarz", "Głowa", "Ciało", "Skóra", "Brwi"]],
    ["Czyścioch", ["Porządek", "Czysty", "Sprzątanie", "Dbałość", "Dyscyplina"]],
    ["Czat", ["Internet", "Komunikacja", "Wiadomość", "Rozmowa", "Komputer"]],
    ["Cyprys", ["Drzewo", "Zielony", "Ogrodnictwo", "Roślina", "Liście"]],
    ["Cyrk", ["Artysta", "Klaun", "Pokaz", "Namiot", "Zwierzę"]],
    ["Cywilizacja", ["Społeczeństwo", "Kultura", "Historia", "Rozwój", "Technologia"]],
    ["Cynik", ["Osoba", "Podejrzliwy", "Nieufny", "Pesymista", "Sarkastyczny"]],
    ["Chrupek", ["Przekąska", "Słony", "Jedzenie", "Chips", "Kukurydza"]],
    ["Chorągiewka", ["Flaga", "Symbol", "Kraj", "Wiatr", "Znak"]],
    ["Cytrynka", ["Motyl", "Insekt", "Żółty", "Lot", "Kwiat"]],
    ["Cesarz", ["Władca", "Imperium", "Monarchia", "Rzym", "Korona"]],
    ["Cesarskie cięcie", ["Poród", "Szpital", "Lekarz", "Dziecko", "Operacja"]],
    ["Cymbałki", ["Instrument", "Muzyka", "Dźwięk", "Orkiestra", "Perkusja"]],
    ["Cyfrowy", ["Elektronika", "Komputer", "Technologia", "Dane", "Binarny"]],
    ["Cykl", ["Seria", "Powtarzanie", "Faza", "Okrąg", "Proces"]],
    ["Cynizm", ["Postawa", "Sarkazm", "Negatywność", "Pesymizm", "Krytyka"]],
    ["Czajnik elektryczny", ["Kuchnia", "Woda", "Elektryczność", "Herbata", "Gorący"]],
    ["Czereśnia", ["Drzewo", "Owoc", "Czerwony", "Wiśnia", "Letni"]],
    ["Czerwona armia", ["ZSRR", "Wojna", "Armia", "Czerwony", "II Wojna Światowa"]],
    ["Czerwony Kapturek", ["Baśń", "Wilkołak", "Dziewczyna", "Babcia", "Las"]],
    ["Czterolistna koniczyna", ["Szczęście", "Roślina", "Zielony", "Irlandia", "Symbol"]],
    ["Cukier puder", ["Cukier", "Gotowanie", "Ciasto", "Słodki", "Deser"]],
    ["Czeladnik", ["Zawód", "Mistrz", "Rzemiosło", "Uczeń", "Praca"]],
    ["Czerep", ["Kości", "Głowa", "Ciało", "Szkielet", "Mózg"]],
    ["Czerniak", ["Choroba", "Skóra", "Nowotwór", "Lekarz", "Zdrowie"]],
    ["Czwórka", ["Numer", "Cztery", "Liczba", "Matematyka", "Zbiór"]],
    ["Czujka", ["Alarm", "Bezpieczeństwo", "Detektor", "System", "Technologia"]],
    ["Cynfolia", ["Materiał", "Metal", "Folia", "Opakowanie", "Kuchnia"]],
    ["Czołówka", ["Lampa", "Światło", "Głowa", "Noc", "Turystyka"]],
    ["Czart", ["Diabeł", "Zło", "Piekielny", "Religia", "Mity"]],
    ["Czempion", ["Mistrz", "Zwycięzca", "Sport", "Sukces", "Konkurencja"]],
    ["Czop", ["Zatkać", "Zatkany", "Przeszkoda", "Rura", "Otwór"]],
    ["Cebulak", ["Roślina", "Ogrodnictwo", "Kwiat", "Ziemia", "Ogrodnik"]],
    ["Czochranie", ["Włosy", "Ręka", "Głowa", "Dotyk", "Zachowanie"]],
    ["Czosnek", ["Kuchnia", "Smak", "Przyprawa", "Warzywo", "Ząbek"]],
    ["Czernina", ["Zupa", "Kuchnia", "Kaczka", "Polska", "Tradycja"]],
    ["Czarny rynek", ["Nielegalny", "Handel", "Towar", "Przestępstwo", "Zakaz"]],
    ["Czarnobyl", ["Katastrofa", "Reaktor", "Radiacja", "Ukraina", "Elektrownia jądrowa"]],
    ["Cedrowy", ["Drzewo", "Cedr", "Zapach", "Drewno", "Las"]],
    ["Cenzura", ["Zakaz", "Władza", "Media", "Informacja", "Ograniczenie"]],
    ["Celownik", ["Broń", "Strzał", "Cel", "Widok", "Precyzja"]],
    ["Cyfrowa waluta", ["Bitcoin", "Internet", "Pieniądze", "Blockchain", "Transakcja"]],
    ["Czółenko", ["Obuwie", "Moda", "Stopa", "Kobieta", "But"]],
    ["Cyklon", ["Pogoda", "Wiatr", "Burza", "Katastrofa", "Atmosfera"]],
    ["Czytelnia", ["Biblioteka", "Książka", "Czytanie", "Wiedza", "Spokój"]],
    ["Czarcie ziółko", ["Roślina", "Zioło", "Kuchnia", "Smak", "Przyprawa"]],
    ["Czterokołowiec", ["Pojazd", "Offroad", "Jazda", "Silnik", "Teren"]],
    ["Cynk", ["Metal", "Pierwiastek", "Chemia", "Minerał", "Korozja"]],
    ["Członkostwo", ["Grupa", "Organizacja", "Członek", "Prawa", "Przynależność"]],
    ["Czarci pazur", ["Roślina", "Zioło", "Leczenie", "Medycyna", "Zdrowie"]],
    ["Czerepak", ["Roślina", "Ogrodnictwo", "Drzewo", "Owoc", "Jesień"]],
    ["Cyklista", ["Rower", "Sport", "Jazda", "Droga", "Zawody"]],
    ["Czopuch", ["Kominek", "Ogień", "Dym", "Palenie", "Dom"]],
    ["Czara", ["Naczynie", "Picie", "Kubek", "Porcelana", "Herbata"]],
    ["Czynnik", ["Element", "Składnik", "Przyczyna", "Efekt", "Rola"]],
    ["Cywilizacja", ["Społeczeństwo", "Historia", "Kultura", "Rozwój", "Ludzie"]],
    ["Czad", ["Tlenek węgla", "Trujący", "Bezbarwny", "Zagrożenie", "Palnik"]],
    ["Czerw", ["Robak", "Insekt", "Ryba", "Przyroda", "Jedzenie"]],
    ["Cerata", ["Pokrowiec", "Ochrona", "Stół", "Materiał", "Plastik"]],
    ["Cukrzyk", ["Cukrzyca", "Choroba", "Insulina", "Cukier", "Zdrowie"]],
    ["Cyrkulator", ["Kuchnia", "Gotowanie", "Podciśnienie", "Temperatura", "Jedzenie"]],
    ["Cyrulik", ["Fryzjer", "Włosy", "Zawód", "Nożyczki", "Strzyżenie"]],
    ["Czajka", ["Ptak", "Przyroda", "Lęgowisko", "Lot", "Dzwonienie"]],
    ["Cysterna", ["Pojazd", "Transport", "Ciecz", "Paliwo", "Pojemnik"]],
    ["Cytrynian", ["Chemia", "Cytryna", "Kwas", "Reakcja", "Pierwiastek"]],
    ["Czokolada", ["Deser", "Słodki", "Kakao", "Tabliczka", "Mleko"]],
    ["Cząber", ["Roślina", "Zioło", "Przyprawa", "Kuchnia", "Smak"]],
    ["Czubatka", ["Ptak", "Hodowla", "Kogut", "Jajko", "Kura"]],
    ["Cyganeria", ["Społeczność", "Romowie", "Kultura", "Tradycja", "Muzyka"]],
    ["Czarna dziura", ["Kosmos", "Grawitacja", "Galaktyka", "Astronomia", "Gwiazda"]],
    ["Czekoladziarnik", ["Insekt", "Szkołka", "Roślina", "Szkodnik", "Owoc"]],
    ["Cyrkonia", ["Minerał", "Kamień", "Biżuteria", "Ozdoba", "Twardość"]],
    ["Czynsz", ["Mieszkanie", "Płatność", "Wynajem", "Właściciel", "Nieruchomość"]],
    ["Cymbergaj", ["Gra", "Tarcza", "Krążek", "Sport", "Ruch"]],
    ["Cytryna", ["Owoc", "Kwaśny", "Citrus", "Żółty", "Sok"]],
    ["Cynober", ["Kolor", "Czerwony", "Pigment", "Malarstwo", "Farba"]],
    ["Czardasz", ["Taniec", "Muzyka", "Węgry", "Folklor", "Zabawa"]],
    ["Czarny kot", ["Zwierzę", "Domowe", "Pech", "Legenda", "Futro"]],
    ["Ciekawość", ["Emocja", "Nauka", "Zainteresowanie", "Wiedza", "Pytanie"]],
    ["Cebula", ["Warzywo", "Kuchnia", "Smak", "Gotowanie", "Zupa"]],
    ["Czarci Pazur", ["Roślina", "Zioło", "Leczenie", "Medycyna", "Zdrowie"]],
    ["Czujnik", ["Urządzenie", "Technologia", "Pomiar", "Elektronika", "Sygnał"]],
    ["Cztery pory roku", ["Zima", "Wiosna", "Lato", "Jesień", "Klimat"]],
    ["Ciepłota", ["Temperatura", "Ciepło", "Zimno", "Termostat", "Pomiar"]],
    ["Ciekły azot", ["Chemia", "Zimny", "Temperatura", "Laboratorium", "Płyn"]],
    ["Czwarty wymiar", ["Przestrzeń", "Czas", "Fizyka", "Teoria względności", "Nauka"]],

    ["Dinozaur", ["Prehistoria", "Wymarły", "Jurajski", "Paleontologia", "Szkielet"]],              //*********************  D  *********************** */
    ["Drewno", ["Drzewo", "Materiał", "Meble", "Las", "Sekator"]],
    ["Dżem", ["Owoce", "Słodki", "Słoik", "Kanapka", "Cukier"]],
    ["Dzwonek", ["Dźwięk", "Słyszeć", "Alarm", "Szkoła", "Drzwi"]],
    ["Deszcz", ["Woda", "Pogoda", "Chmury", "Parasol", "Mokry"]],
    ["Dżinsy", ["Spodnie", "Moda", "Bawełna", "Niebieski", "Ubieranie"]],
    ["Długopis", ["Pisanie", "Tusz", "Papier", "Notatki", "Szkolny"]],
    ["Diament", ["Kamień", "Szczoteczka", "Cenny", "Biżuteria", "Twardy"]],
    ["Dzbanek", ["Naczynie", "Woda", "Pojemnik", "Napój", "Szklany"]],
    ["Dzik", ["Zwierzę", "Las", "Łowny", "Tusze", "Dziki"]],
    ["Dreptak", ["Spacer", "Wolny", "Relaks", "Ruch", "Dystans"]],
    ["Drożdże", ["Pieczywo", "Pieczenie", "Ciasto", "Fermentacja", "Piekarnik"]],
    ["Dalmatyńczyk", ["Pies", "Rasa", "Kropki", "Film", "Zwierzę"]],
    ["Dach", ["Dom", "Budynek", "Ochrona", "Dachówka", "Budowa"]],
    ["Dorsz", ["Ryba", "Morze", "Jedzenie", "Wędkowanie", "Gotowanie"]],
    ["Debata", ["Dyskusja", "Argumenty", "Rozmowa", "Polityka", "Sprzeczka"]],
    ["Dowód", ["Prawda", "Argument", "Sąd", "Fakty", "Zeznanie"]],
    ["Dydaktyka", ["Nauczanie", "Edukacja", "Metoda", "Szkoła", "Zasady"]],
    ["Dysk", ["Komputer", "Pamięć", "Dane", "Zapis", "Twardy"]],
    ["Dżdżysty", ["Pogoda", "Deszcz", "Mokry", "Chmury", "Parasol"]],
    ["Dźwig", ["Budowa", "Podnoszenie", "Ciężar", "Maszyna", "Wysokość"]],
    ["Daktyle", ["Owoc", "Słodki", "Pustynia", "Palma", "Suszone"]],
    ["Dziurkacz", ["Biuro", "Papier", "Dziura", "Narzędzie", "Dokument"]],
    ["Dzieło", ["Sztuka", "Tworzenie", "Praca", "Artysta", "Obraz"]],
    ["Diabeł", ["Zło", "Religia", "Piekieł", "Czerwony", "Róg"]],
    ["Duszność", ["Oddychanie", "Zdrowie", "Płuca", "Tlen", "Lekarz"]],
    ["Dieta", ["Jedzenie", "Zdrowie", "Kalorie", "Odchudzanie", "Sport"]],
    ["Dawka", ["Lek", "Zdrowie", "Lekarz", "Medycyna", "Szpital"]],
    ["Dres", ["Ubranie", "Sport", "Bieganie", "Moda", "Trening"]],
    ["Dekolt", ["Ubranie", "Moda", "Kobieta", "Sukienka", "Biust"]],
    ["Dąb", ["Drzewo", "Las", "Natura", "Drewno", "Liście"]],
    ["Dewiacja", ["Zachowanie", "Społeczeństwo", "Psychologia", "Norma", "Zasady"]],
    ["Dalmacja", ["Chorwacja", "Morze", "Wakacje", "Podróż", "Turystyka"]],
    ["Dywan", ["Podłoga", "Dom", "Dekoracja", "Pokój", "Wełna"]],
    ["Dziennik", ["Gazeta", "News", "Informacje", "Czytanie", "Media"]],
    ["Dyplomacja", ["Polityka", "Stosunki międzynarodowe", "Ambasador", "Negocjacje", "Rząd"]],
    ["Delegacja", ["Podróż służbowa", "Praca", "Firma", "Zadanie", "Biznes"]],
    ["Detektyw", ["Śledztwo", "Kryminał", "Policja", "Zagadka", "Dowody"]],
    ["Dalmierz", ["Pomiar", "Dystans", "Narzędzie", "Budowa", "Technologia"]],
    ["Dyskusja", ["Rozmowa", "Argumenty", "Debata", "Rozwaga", "Opinia"]],
    ["Dziedzictwo", ["Spadek", "Historia", "Rodzina", "Kultura", "Tradycja"]],
    ["Demokracja", ["Polityka", "Rząd", "Wybory", "Głosowanie", "Społeczeństwo"]],
    ["Dywersja", ["Sabotaż", "Wojna", "Szpiegostwo", "Strategia", "Konflikt"]],
    ["Działka", ["Ogród", "Przyroda", "Warzywa", "Wypoczynek", "Grunt"]],
    ["Dziekanat", ["Szkoła", "Studia", "Sekretariat", "Dokumenty", "Edukacja"]],
    ["Depozyt", ["Bank", "Pieniądze", "Inwestycja", "Oszczędności", "Rachunek"]],
    ["Dynamit", ["Eksplozja", "Bomba", "Wybuch", "Niebezpieczny", "Niszczenie"]],
    ["Destylacja", ["Proces", "Chemia", "Ciecz", "Alkohol", "Laboratorium"]],
    ["Dekalog", ["Religia", "Biblia", "Zasady", "Chrześcijaństwo", "Przykazania"]],
    ["Dylemat", ["Problem", "Decyzja", "Wybór", "Rozważania", "Konflikt"]],
    ["Drukarka", ["Papier", "Atrament", "Komputer", "Drukowanie", "Tekst"]],
    ["Dalmierz", ["Odległość", "Pomiar", "Budowa", "Narzędzie", "Technologia"]],
    ["Domino", ["Gra", "Kamienie", "Strategia", "Rozrywka", "Numer"]],
    ["Dzban", ["Woda", "Naczynie", "Pojemnik", "Napój", "Ceramika"]],
    ["Dzieciństwo", ["Młodość", "Wspomnienia", "Zabawa", "Szkoła", "Rodzina"]],
    ["Dreszczyk", ["Emocje", "Strach", "Ekscytacja", "Zimno", "Napięcie"]],
    ["Dystrykt", ["Obszar", "Region", "Miasto", "Administracja", "Terytorium"]],
    ["Dekret", ["Zasada", "Prawo", "Rząd", "Dokument", "Ustawa"]],
    ["Dywanik", ["Podłoga", "Dekoracja", "Dom", "Pokój", "Tkanina"]],
    ["Dźwiękoszczelny", ["Cichy", "Izolacja", "Hałas", "Pokój", "Ściana"]],
    ["Dwór", ["Budynek", "Historia", "Szlachta", "Pole", "Starożytność"]],
    ["Dygresja", ["Rozmowa", "Odstępstwo", "Temat", "Rozproszenie", "Konwersacja"]],
    ["Dokumentacja", ["Papier", "Dokument", "Informacja", "Szczegóły", "Projekt"]],
    ["Dyskoteka", ["Muzyka", "Taniec", "Zabawa", "Noc", "DJ"]],
    ["Dekada", ["Lata", "Dziesięć", "Czas", "Epoka", "Historia"]],
    ["Dedukcja", ["Logika", "Rozumowanie", "Wnioskowanie", "Zasada", "Zakluczenie"]],
    ["Dżungla", ["Las", "Tropiki", "Zwierzęta", "Rośliny", "Deszcz"]],
    ["Dystopia", ["Futurystyczny", "Społeczeństwo", "Literatura", "Negatywny", "Przyszłość"]],
    ["Dobosz", ["Bęben", "Muzyka", "Orkiestra", "Rytm", "Instrument"]],
    ["Dyktafon", ["Nagrywanie", "Głos", "Urządzenie", "Dźwięk", "Notatki"]],
    ["Dział", ["Sekcja", "Departament", "Firma", "Praca", "Organizacja"]],
    ["Dewastacja", ["Zniszczenie", "Katastrofa", "Szok", "Ruiny", "Szkoda"]],
    ["Dyplomat", ["Ambasador", "Rząd", "Polityka", "Stosunki międzynarodowe", "Negocjacje"]],
    ["Dziekan", ["Uniwersytet", "Edukacja", "Wydział", "Nauczyciel", "Zarządzanie"]],
    ["Dżentelmen", ["Mężczyzna", "Uprzejmość", "Elegancja", "Kultura", "Respekt"]],
    ["Detonacja", ["Wybuch", "Bomba", "Eksplozja", "Niszczenie", "Hałas"]],
    ["Dekagon", ["Kształt", "Dziesięć", "Geometria", "Boki", "Kąt"]],
    ["Dekalog", ["Dziesięć", "Prawa", "Biblia", "Religia", "Przykazania"]],
    ["Dermatologia", ["Skóra", "Medycyna", "Lekarz", "Zdrowie", "Choroba"]],
    ["Dyskwalifikacja", ["Sport", "Konkurs", "Zasady", "Przegrana", "Zakaz"]],
    ["Dzień", ["Czas", "Słońce", "Godziny", "Światło", "Noc"]],
    ["Dyplom", ["Certyfikat", "Ukończenie", "Szkoła", "Edukacja", "Nagroda"]],
    ["Deklaracja", ["Oświadczenie", "Prawo", "Zgoda", "Umowa", "Zobowiązanie"]],
    ["Dubler", ["Aktorka", "Film", "Podobieństwo", "Scena", "Zastępstwo"]],
    ["Dewiza", ["Hasło", "Motto", "Zasada", "Cytat", "Słowa"]],
    ["Dystrybucja", ["Rozprowadzanie", "Produkt", "Biznes", "Sprzedaż", "Dostawca"]],
    ["Dachówka", ["Dach", "Budowa", "Budynek", "Materiał", "Pokrycie"]],
    ["Dynamika", ["Ruch", "Energia", "Siła", "Fizyka", "Prędkość"]],
    ["Diuretyk", ["Lek", "Płyny", "Nerki", "Zdrowie", "Medycyna"]],
    ["Dezynfekcja", ["Czystość", "Bakterie", "Zdrowie", "Higiena", "Czysty"]],
    ["Długotrwały", ["Czas", "Stabilność", "Trwałość", "Długo", "Wytrzymałość"]],
    ["Dyskryminacja", ["Niesprawiedliwość", "Rasa", "Płeć", "Zasady", "Społeczeństwo"]],
    ["Dyplomacja", ["Polityka", "Stosunki międzynarodowe", "Negocjacje", "Ambasador", "Takt"]],
    ["Dżem", ["Owoce", "Słodki", "Śniadanie", "Chleb", "Konserwacja"]],
    ["Dzbanek", ["Woda", "Pojemnik", "Napój", "Ceramika", "Kuchnia"]],
    ["Dysydent", ["Opozycja", "Rząd", "Polityka", "Rebeliant", "Protest"]],
    ["Dysonans", ["Muzyka", "Dźwięk", "Harmonia", "Nieharmoniczny", "Ton"]],
    ["Dywersja", ["Rozproszenie", "Taktyka", "Strategia", "Zwiedzenie", "Wojna"]],
    ["Dźwig", ["Budowa", "Podniesienie", "Maszyna", "Ciężar", "Wysokość"]],
    ["Dykcja", ["Mowa", "Wymowa", "Głos", "Artysta", "Dialog"]],
    ["Dyfuzja", ["Rozprzestrzenianie", "Ruch", "Molekuły", "Nauka", "Koncentracja"]],
    ["Detektyw", ["Śledztwo", "Zbrodnia", "Policja", "Tajemnica", "Dowody"]],
    ["Debata", ["Dyskusja", "Argument", "Polityka", "Mowa", "Problem"]],
    ["Dekret", ["Prawo", "Zasada", "Rząd", "Dokument", "Ustawa"]],
    ["Dynastia", ["Rodzina", "Władza", "Królewski", "Historia", "Sukcesja"]],
    ["Dyplomata", ["Ambasador", "Polityka", "Negocjacje", "Rząd", "Stosunki międzynarodowe"]],
    ["Dynamit", ["Eksplozja", "Wybuch", "Energia", "Niebezpieczny", "Niszczenie"]],

    ["Edukacja", ["Szkoła", "Nauka", "Nauczyciel", "Student", "Zadanie"]],                          //***********************  E  ************************** */
    ["Ekran", ["Telewizor", "Komputer", "Obraz", "Monitor", "Projektor"]],
    ["Ekosystem", ["Natura", "Zwierzęta", "Rośliny", "Środowisko", "Bioróżnorodność"]],
    ["Ekonomia", ["Pieniądze", "Biznes", "Rynek", "Produkcja", "Konsumpcja"]],
    ["Elektryczność", ["Prąd", "Światło", "Energia", "Lampka", "Wtyczka"]],
    ["Element", ["Część", "Komponent", "Składnik", "Atom", "Materiał"]],
    ["Emocje", ["Czucie", "Radość", "Smutek", "Wściekłość", "Miłość"]],
    ["Energia", ["Siła", "Moc", "Elektryczność", "Ciepło", "Źródło"]],
    ["Epoka", ["Czas", "Era", "Historyczny", "Wieki", "Pokolenie"]],
    ["Egzamin", ["Test", "Nauka", "Pytania", "Odpowiedzi", "Szkoła"]],
    ["Eksperyment", ["Badania", "Nauka", "Laboratorium", "Test", "Hipoteza"]],
    ["Ekspres", ["Pociąg", "Szybki", "Podróż", "Transport", "Tor"]],
    ["Elegancja", ["Styl", "Moda", "Piękno", "Sofistyka", "Klasa"]],
    ["Elefant", ["Zwierzę", "Słoń", "Duży", "Afryka", "Zoo"]],
    ["Elita", ["Najlepsi", "Grupa", "Prestiż", "Pierwszy", "Wyjątkowy"]],
    ["Emigracja", ["Wyjazd", "Kraj", "Zagranica", "Praca", "Zmiana"]],
    ["Ewolucja", ["Zmiana", "Nauka", "Rozwój", "Gatunek", "Darwin"]],
    ["Ekstrawagancja", ["Ekstremalne", "Szał", "Nietypowy", "Odmienny", "Pokazowy"]],
    ["Egzorcysta", ["Kościół", "Zło", "Demon", "Duch", "Rytuał"]],
    ["Ekstrakt", ["Esencja", "Wyciąg", "Składnik", "Kondensat", "Destylat"]],
    ["Euforia", ["Radość", "Szczęście", "Emocje", "Podniecenie", "Wzruszenie"]],
    ["Eskadra", ["Flota", "Statki", "Marynarka wojenna", "Grupa", "Formacja"]],
    ["Ekliptyka", ["Astronomia", "Ziemia", "Słońce", "Orbita", "Wszechświat"]],
    ["Estetyka", ["Piękno", "Sztuka", "Wrażenie", "Ocena", "Gust"]],
    ["Ekspedycja", ["Podróż", "Przygoda", "Odkrycie", "Misja", "Wyprawa"]],
    ["Encyklopedia", ["Wiedza", "Książka", "Informacja", "Definicja", "Zasób"]],
    ["Entuzjazm", ["Radość", "Ekscytacja", "Zapał", "Interes", "Pasja"]],
    ["Eskimos", ["Lud", "Arktyka", "Lód", "Igloo", "Zimno"]],
    ["Egzekucja", ["Kara", "Śmierć", "Wyrok", "Prawo", "Zbrodnia"]],
    ["Ekranizacja", ["Film", "Książka", "Reżyser", "Scenariusz", "Aktorzy"]],
    ["Egzotyka", ["Odległy", "Nieznany", "Zaskakujący", "Intrygujący", "Oryginalny"]],
    ["Egzemplarz", ["Kopia", "Produkt", "Model", "Wersja", "Jednostka"]],
    ["Epidemia", ["Choroba", "Zarażenie", "Zdrowie", "Wirus", "Pandemia"]],
    ["Etiologia", ["Przyczyna", "Choroba", "Nauka", "Badanie", "Diagnoza"]],
    ["Etyka", ["Moralność", "Zasady", "Dobre", "Złe", "Filozofia"]],
    ["Euforia", ["Szczęście", "Radość", "Ekscytacja", "Nastroj", "Optymizm"]],
    ["Ewakuacja", ["Wyjście", "Bezpieczeństwo", "Kryzys", "Alarm", "Ucieczka"]],
    ["Ekwiwalent", ["Równy", "Odpowiednik", "Zamiennik", "Porównywalny", "Równoważny"]],
    ["Ekumenizm", ["Religia", "Jedność", "Współpraca", "Kościół", "Wiara"]],
    ["Egzystencjalizm", ["Filozofia", "Istnienie", "Życie", "Sens", "Wolność"]],
    ["Ekstradycja", ["Prawo", "Zbrodnia", "Wydanie", "Sąd", "Przestępstwo"]],
    ["Ekscytacja", ["Radość", "Podekscytowanie", "Napięcie", "Oczekiwanie", "Wzruszenie"]],
    ["Ekstremum", ["Kres", "Limit", "Maksimum", "Minimum", "Ostatni"]],
    ["Eksplozja", ["Wybuch", "Dynamit", "Bomba", "Zniszczenie", "Ogień"]],
    ["Elastyczność", ["Rozciągliwość", "Giętkość", "Adaptacyjność", "Sprężystość", "Ugięcie"]],
    ["Emblemat", ["Symbol", "Znak", "Herb", "Logo", "Godło"]],
    ["Emanacja", ["Wygląd", "Promieniowanie", "Aura", "Światło", "Wyrażenie"]],
    ["Empatia", ["Zrozumienie", "Czuć", "Współczucie", "Reakcja", "Troska"]],
    ["Endemia", ["Choroba", "Lokalizacja", "Epidemia", "Zakres", "Zdrowie"]],
    ["Erotyzm", ["Seksualność", "Pociąg", "Namiętność", "Zmysłowość", "Miłość"]],
    ["Egzekutor", ["Wykonawca", "Sąd", "Kara", "Zadanie", "Wyrok"]],
    ["Ekscelencja", ["Tytuł", "Szacunek", "Ranga", "Kościół", "Dostojnik"]],
    ["Edytor", ["Tekst", "Program", "Kod", "Komputer", "Zapis"]],
    ["Egzaminator", ["Test", "Nauczyciel", "Sprawdzanie", "Ocena", "Student"]],
    ["Elektorat", ["Wyborcy", "Wybory", "Głosowanie", "Polityka", "Grupa"]],
    ["Elektroliza", ["Chemia", "Prąd", "Reakcja", "Rozkład", "Woda"]],
    ["Emerytura", ["Praca", "Starość", "Pieniądze", "Rentowność", "Przychód"]],
    ["Endoskopia", ["Badanie", "Medycyna", "Wizualizacja", "Choroba", "Instrument"]],
    ["Entropia", ["Fizyka", "Zasada", "Chaos", "Porządek", "Ciepło"]],
    ["Eremita", ["Samotnik", "Osamotnienie", "Pustelnik", "Ciche", "Spokojne"]],
    ["Erudyta", ["Wiedza", "Uczony", "Inteligencja", "Książki", "Nauka"]],
    ["Eskalator", ["Schody", "Ruch", "Wzrost", "Centrum handlowe", "Transport"]],
    ["Eskorta", ["Ochrona", "Pomoc", "Bezpieczeństwo", "Towarzystwo", "Pomoc"]],
    ["Esperanto", ["Język", "Międzynarodowy", "Komunikacja", "Słownik", "Gramatyka"]],
    ["Etykietka", ["Tag", "Informacja", "Produkt", "Cena", "Znak"]],
    ["Eufemizm", ["Słowo", "Zastąpienie", "Grzeczność", "Wyrażenie", "Sens"]],
    ["Ewakuacja", ["Ucieczka", "Kryzys", "Bezpieczeństwo", "Alarm", "Ruch"]],
    ["Ekologia", ["Natura", "Ochrona", "Zasoby", "Zanieczyszczenie", "Zrównoważenie"]],
    ["Etologia", ["Zwierzęta", "Behawior", "Nauka", "Zachowanie", "Studium"]],
    ["Epistemologia", ["Wiedza", "Filozofia", "Nauka", "Zrozumienie", "Teoria"]],
    ["Egzaltacja", ["Podniecenie", "Ekscytacja", "Pasja", "Euforia", "Wzruszenie"]],
    ["Egzorcyzm", ["Religia", "Demony", "Rytuał", "Duchy", "Czystość"]],
    ["Egzystencja", ["Istnienie", "Życie", "Byt", "Rzeczywistość", "Trwanie"]],
    ["Ekspansja", ["Rozwój", "Wzrost", "Powiększenie", "Podbój", "Szerzenie"]],
    ["Ekstaza", ["Radość", "Euforia", "Szczęście", "Podniecenie", "Błogość"]],
    ["Egzorcysta", ["Duch", "Kościół", "Wygnanie", "Rytuał", "Demon"]],
    ["Ekran", ["Monitor", "Obraz", "Telewizja", "Komputer", "Projekcja"]],
    ["Ekosfera", ["Ziemia", "Ekosystem", "Środowisko", "Natura", "Biosfera"]],
    ["Elektryzowanie", ["Prąd", "Ładowanie", "Energia", "Iskra", "Napięcie"]],
    ["Eliptyczny", ["Kształt", "Okrąg", "Geometryczny", "Orbita", "Krzywa"]],
    ["Emblemat", ["Symbol", "Logo", "Znak", "Godło", "Herb"]],
    ["Emocja", ["Czucie", "Reakcja", "Serce", "Złość", "Radość"]],
    ["Empatia", ["Zrozumienie", "Czucie", "Współczucie", "Ludzie", "Reakcja"]],
    ["Enklawa", ["Terytorium", "Kraj", "Granica", "Izolacja", "Państwo"]],
    ["Energia", ["Moc", "Prąd", "Siła", "Zasób", "Paliwo"]],
    ["Entuzjasta", ["Fan", "Zapał", "Pasja", "Miłość", "Zainteresowanie"]],
    ["Epidemia", ["Choroba", "Zdrowie", "Zarażenie", "Wirus", "Szpital"]],
    ["Epizod", ["Część", "Seria", "Program", "Sezon", "Scenariusz"]],
    ["Era", ["Okres", "Czas", "Historia", "Wiek", "Pokolenie"]],
    ["Esencja", ["Podstawa", "Klucz", "Najważniejszy", "Dusza", "Zasada"]],
    ["Eskadra", ["Flota", "Statki", "Armia", "Morski", "Grupa"]],
    ["Eskadron", ["Kawaleria", "Grupa", "Wojsko", "Jednostka", "Konie"]],
    ["Eskapada", ["Przygoda", "Podróż", "Wyprawa", "Spree", "Wyjazd"]],
    ["Eskorta", ["Ochrona", "Pomoc", "Bezpieczeństwo", "Ochroniarz", "Towarzystwo"]],
    ["Espresso", ["Kawa", "Napój", "Gorący", "Kawiarnia", "Włoski"]],
    ["Esteta", ["Sztuka", "Piękno", "Smak", "Kultura", "Wrażliwość"]],
    ["Etui", ["Pokrowiec", "Ochrona", "Obudowa", "Skórzany", "Telefon"]],
    ["Eutanazja", ["Śmierć", "Medycyna", "Cierpienie", "Pomoc", "Życie"]],
    ["Ewangelia", ["Biblia", "Chrześcijaństwo", "Kościół", "Jezus", "Wiara"]],
    ["Ewolucja", ["Rozwój", "Zmiana", "Nauka", "Darwin", "Gatunek"]],

    ["Fasola", ["Jedzenie", "Roślina", "Gotowanie", "Zupa", "Nasiona"]],                        //***********************  F  ********************* */
    ["Film", ["Kino", "Aktor", "Reżyser", "Scenariusz", "Kamera"]],
    ["Fotel", ["Siedzenie", "Mebel", "Pokój", "Komfort", "Poduszka"]],
    ["Fryzjer", ["Włosy", "Strzyżenie", "Salon", "Nożyczki", "Fryzura"]],
    ["Fizyka", ["Nauka", "Eksperyment", "Atom", "Energia", "Teoria"]],
    ["Fortepian", ["Muzyka", "Instrument", "Klawisze", "Koncert", "Melodia"]],
    ["Faraon", ["Egipt", "Król", "Piramida", "Sfinks", "Mumia"]],
    ["Fundacja", ["Organizacja", "Dobroczynność", "Darowizna", "Cel", "Wsparcie"]],
    ["Farma", ["Zwierzęta", "Rolnik", "Pole", "Zboże", "Traktor"]],
    ["Finał", ["Koniec", "Zwycięstwo", "Mecz", "Rozgrywki", "Puchar"]],
    ["Figura", ["Kształt", "Rysunek", "Geometria", "Sylwetka", "Wykres"]],
    ["Futro", ["Zwierzę", "Ciepło", "Odzież", "Kurtka", "Zimowy"]],
    ["Feniks", ["Mitologia", "Ptak", "Ogień", "Odrodzenie", "Legenda"]],
    ["Fotografia", ["Obraz", "Kamera", "Zdjęcie", "Aparat", "Studio"]],
    ["Fantazja", ["Wyobraźnia", "Marzenie", "Myśl", "Ideia", "Kreatywność"]],
    ["Frytki", ["Jedzenie", "Ziemniaki", "Smak", "Smażenie", "Restauracja"]],
    ["Falowanie", ["Ruch", "Fala", "Woda", "Oscylacja", "Powtarzanie"]],
    ["Flota", ["Statki", "Marynarka", "Morze", "Armia", "Transport"]],
    ["Flaming", ["Ptak", "Różowy", "Stojący", "Noga", "Jezioro"]],
    ["Flet", ["Muzyka", "Instrument", "Dęty", "Dźwięk", "Orkiestra"]],
    ["Ferajna", ["Gang", "Grupa", "Przyjaciele", "Towarzystwo", "Zbiorowość"]],
    ["Fauna", ["Zwierzęta", "Natura", "Ekosystem", "Bioróżnorodność", "Dziki"]],
    ["Fenomen", ["Zjawisko", "Wyjątkowy", "Niezwykły", "Obserwacja", "Studium"]],
    ["Fregata", ["Statek", "Żaglowiec", "Morze", "Marynarka", "Podróż"]],
    ["Frymarczyć", ["Zdradzać", "Nieuczciwość", "Romans", "Związek", "Kłamstwo"]],
    ["Fiołek", ["Kwiat", "Roślina", "Fioletowy", "Ogrodnictwo", "Zapach"]],
    ["Fajka", ["Palenie", "Tytoń", "Dym", "Szklanka", "Komin"]],
    ["Formuła", ["Równanie", "Matematyka", "Zasada", "Chemia", "Nauka"]],
    ["Franczyza", ["Biznes", "Marka", "Prawa", "Sklep", "Umowa"]],
    ["Frukt", ["Owoc", "Jedzenie", "Zdrowie", "Słodki", "Sałatka"]],
    ["Futbol", ["Sport", "Piłka", "Gra", "Drużyna", "Mecz"]],
    ["Fizjoterapia", ["Leczenie", "Zdrowie", "Rehabilitacja", "Ruch", "Terapeuta"]],
    ["Feminizm", ["Równość", "Kobiety", "Ruch", "Prawa", "Społeczeństwo"]],
    ["Filar", ["Podpora", "Budowa", "Architektura", "Kolumna", "Budynek"]],
    ["Funkcja", ["Rola", "Cel", "Zadanie", "Praca", "Działanie"]],
    ["Falafel", ["Jedzenie", "Wegetariański", "Ciecierzyca", "Bliski Wschód", "Smażony"]],
    ["Faktura", ["Rachunek", "Płatność", "Zakupy", "Sprzedaż", "Handel"]],
    ["Forteca", ["Twierdza", "Zamek", "Obrona", "Mur", "Historia"]],
    ["Figiel", ["Psota", "Żart", "Dowcip", "Zabawa", "Szelmowski"]],
    ["Furgonetka", ["Samochód", "Transport", "Pojazd", "Przeprowadzka", "Dostawczy"]],
    ["Fotelarz", ["Mebelarz", "Zawód", "Fotel", "Praca", "Remont"]],
    ["Fiskus", ["Podatek", "Skarb Państwa", "Urząd", "Prawo", "Finanse"]],
    ["Filister", ["Obłuda", "Ciasnota", "Niechęć", "Odmowa", "Zacofany"]],
    ["Familok", ["Budynek", "Mieszkanie", "Rodzina", "Śląsk", "Kopalnia"]],
    ["Fałsz", ["Kłamstwo", "Nieprawda", "Zmyślenie", "Podróbka", "Oszustwo"]],
    ["Fragment", ["Część", "Kawałek", "Ułamek", "Sekcja", "Podział"]],
    ["Fizjonomia", ["Twarz", "Rysy", "Wygląd", "Charakterystyka", "Ekspresja"]],
    ["Fajerwerk", ["Ogień", "Zabawa", "Sylwester", "Pokaz", "Kolory"]],
    ["Feldfebel", ["Wojsko", "Stopień", "Służba", "Podoficer", "Armia"]],
    ["Fluor", ["Pierwiastek", "Chemia", "Ząb", "Fluorki", "Toksyczność"]],
    ["Faktotum", ["Wszystko", "Robota", "Uniwersalny", "Zastępca", "Załatwiać"]],
    ["Fokstrot", ["Taniec", "Muzyka", "Pary", "Kroki", "Rytm"]],
    ["Falstart", ["Błąd", "Start", "Wyścig", "Nielegalny", "Przedwcześnie"]],
    ["Flamaster", ["Pisak", "Kolor", "Rysunek", "Sztuka", "Dziecko"]],
    ["Flejta", ["Flet", "Muzyka", "Instrument", "Dźwięk", "Melodia"]],
    ["Frekwencja", ["Uczęszczanie", "Obecność", "Udział", "Częstotliwość", "Zdarzenie"]],
    ["Futerał", ["Pokrowiec", "Ochrona", "Obudowa", "Etui", "Instrument"]],
    ["Figlarny", ["Szelmiacki", "Żartobliwy", "Wesoły", "Zabawny", "Niesforny"]],
    ["Faktoring", ["Finanse", "Dług", "Transakcja", "Zobowiązanie", "Rachunek"]],
    ["Fryz", ["Fryzura", "Włosy", "Styl", "Strzyżenie", "Głowa"]],
    ["Frenologia", ["Nauka", "Mózg", "Psychologia", "Charakter", "Czaszka"]],
    ["Futbol", ["Piłka", "Mecz", "Bramka", "Boisko", "Drużyna"]],
    ["Fizyka", ["Nauka", "Atomy", "Energia", "Grawitacja", "Prędkość"]],
    ["Flaming", ["Ptak", "Różowy", "Stojący", "Jedna noga", "Zoo"]],
    ["Fretka", ["Zwierzę", "Domowe", "Drapieżnik", "Ssak", "Długie ciało"]],
    ["Fujara", ["Instrument", "Dęty", "Drewno", "Muzyka", "Słowacja"]],
    ["Fermentacja", ["Proces", "Biologia", "Alkohol", "Drożdże", "Piwo"]],
    ["Fotel", ["Meble", "Siedzenie", "Dom", "Komfort", "Relaks"]],
    ["Farma", ["Zwierzęta", "Rolnik", "Ziemia", "Pole", "Zbiory"]],
    ["Fletnia", ["Instrument", "Dęty", "Muzyka", "Dźwięk", "Drewno"]],
    ["Fototapeta", ["Ściana", "Obraz", "Dekoracja", "Dom", "Wnętrze"]],
    ["Fasola", ["Roślina", "Jedzenie", "Zielona", "Białe nasiona", "Strąk"]],
    ["Farfocel", ["Pies", "Mały", "Słodki", "Zwierzę", "Domowe"]],
    ["Ferajna", ["Grupa", "Zbiorowość", "Ekipa", "Znajomi", "Gang"]],
    ["Fasolka", ["Jedzenie", "Cukierki", "Słodkie", "Różne smaki", "Kolorowe"]],
    ["Freon", ["Chłodzenie", "Gaz", "Klimatyzacja", "Chłodzenie", "Zagrożenie dla ozonu"]],
    ["Finał", ["Koniec", "Zakończenie", "Ostatnia runda", "Mecz", "Decydujący moment"]],
    ["Francja", ["Kraj", "Europa", "Paryż", "Eiffel", "Bagietka"]],
    ["Film", ["Kino", "Aktorzy", "Reżyser", "Scenariusz", "Ekran"]],
    ["Felga", ["Koło", "Samochód", "Metal", "Obręcz", "Opona"]],
    ["Festiwal", ["Wydarzenie", "Muzyka", "Koncerty", "Zbiorowość", "Impreza"]],
    ["Fala", ["Woda", "Ocean", "Morze", "Surfing", "Ruch"]],
    ["Faseta", ["Powierzchnia", "Szczegół", "Aspekt", "Bok", "Cechy"]],
    ["Flora", ["Rośliny", "Przyroda", "Środowisko", "Ziemia", "Ekologia"]],
    ["Fiskus", ["Podatki", "Rząd", "Finanse", "Skarb państwa", "ZUS"]],
    ["Fortepian", ["Instrument", "Muzyka", "Klawisze", "Koncert", "Dźwięk"]],
    ["Fakir", ["Iluzjonista", "Sztuczki", "Magia", "Indie", "Szpilki"]],
    ["Format", ["Rozmiar", "Układ", "Struktura", "Dokument", "Papier"]],
    ["Futbolista", ["Sportowiec", "Piłka nożna", "Mecz", "Zawodnik", "Drużyna"]],
    ["Folklor", ["Tradycje", "Kultura", "Sztuka", "Historia", "Społeczeństwo"]],
    ["Flakon", ["Butelka", "Zapach", "Perfumy", "Szklany", "Kosmetyki"]],
    ["Faktura", ["Dokument", "Zakupy", "Podatek", "Sprzedaż", "Księgowość"]],
    ["Filatelistyka", ["Hobby", "Znaczki", "Kolekcja", "Poczta", "Historia"]],
    ["Ferryt", ["Materiał", "Magnes", "Elektronika", "Indukcja", "Transformator"]],
    ["Faworyt", ["Ulubiony", "Najlepszy", "Zwycięzca", "Pierwszy", "Lider"]],
    ["Fizjologia", ["Nauka", "Ciało", "Organizm", "Zdrowie", "Biologia"]],
    ["Fruktarianizm", ["Dieta", "Owoce", "Zdrowie", "Wegetarianizm", "Etyka"]],
    ["Fenol", ["Chemia", "Związek", "Kwas", "Organiczny", "Zapach"]],
    ["Flegmatyk", ["Temperament", "Osobowość", "Spokój", "Osoba", "Człowiek"]],
    ["Fluoryt", ["Minerał", "Kamień", "Fluor", "Geologia", "Kryształ"]],
    ["Forsa", ["Pieniądze", "Gotówka", "Zasoby", "Bogactwo", "Zamożność"]],

    ["Góra", ["Wysokość", "Wspinaczka", "Szczyt", "Widok", "Zakopane"]],                        //***************************  G  *********************** */
    ["Gazeta", ["News", "Artykuł", "Czytanie", "Dziennikarz", "Papier"]],
    ["Głowa", ["Mózg", "Twarz", "Myślenie", "Ciało", "Włosy"]],
    ["Gwiazda", ["Noc", "Niebo", "Kosmos", "Planeta", "Teleskop"]],
    ["Gotowanie", ["Jedzenie", "Kucharz", "Przepis", "Kuchnia", "Garnek"]],
    ["Guma", ["Kauczuk", "Elastyczny", "Opona", "Do żucia", "Odbijanie"]],
    ["Granat", ["Owoc", "Broń", "Czerwony", "Eksplozja", "Nasiona"]],
    ["Gra", ["Zabawa", "Planszowa", "Komputerowa", "Zasady", "Gracze"]],
    ["Głos", ["Słuch", "Mówienie", "Piosenka", "Głośny", "Cicho"]],
    ["Guma do żucia", ["Mięta", "Zęby", "Bąbelki", "Słodkie", "Żucie"]],
    ["Grypa", ["Choroba", "Zimno", "Kaszle", "Gorączka", "Leki"]],
    ["Gitara", ["Muzyka", "Instrument", "Struny", "Piosenka", "Koncert"]],
    ["Garnitur", ["Ubranie", "Elegancki", "Spodnie", "Marynarka", "Krawat"]],
    ["Guma do skakania", ["Zabawa", "Skok", "Dzieci", "Podwórko", "Ruch"]],
    ["Grecka", ["Kraj", "Ateny", "Mitologia", "Olimp", "Salatka"]],
    ["Gonitwa", ["Wyścig", "Prędkość", "Zwierzęta", "Konie", "Sport"]],
    ["Garnek", ["Gotowanie", "Kuchnia", "Metal", "Jedzenie", "Pokrywka"]],
    ["Grzyb", ["Las", "Jedzenie", "Kapelusz", "Trujący", "Jadalny"]],
    ["Garaż", ["Samochód", "Budynku", "Miejsce", "Narzędzia", "Parking"]],
    ["Golarka", ["Włosy", "Ciało", "Golenie", "Elektryczna", "Ostrość"]],
    ["Głębia", ["Pod wodą", "Wysokość", "Morze", "Ocean", "Nurkowanie"]],
    ["Granica", ["Państwo", "Linia", "Przekraczanie", "Paszport", "Cło"]],
    ["Gatunek", ["Kategoria", "Typ", "Zwierzęta", "Rośliny", "Klasyfikacja"]],
    ["Gips", ["Budowlany", "Łamać", "Szpital", "Biały", "Rzeźba"]],
    ["Gen", ["DNA", "Biologia", "Dziedziczność", "Rodzice", "Choroby"]],
    ["Galaktyka", ["Kosmos", "Gwiazdy", "Wszechświat", "Droga Mleczna", "Planety"]],
    ["Guma balonowa", ["Żucie", "Dmuchanie", "Słodkie", "Dzieci", "Bąbelki"]],
    ["Gospodarstwo", ["Farmer", "Zwierzęta", "Pole", "Ziemia", "Rolnictwo"]],
    ["Gratka", ["Okazja", "Szansa", "Radość", "Zadowolenie", "Szczęście"]],
    ["Górnictwo", ["Kopalnia", "Węgiel", "Złoto", "Praca", "Maszyny"]],
    ["Gol", ["Piłka nożna", "Mecz", "Bramkarz", "Bramka", "Zwycięstwo"]],
    ["Grafit", ["Ołówek", "Rysowanie", "Czarny", "Minerał", "Elektroda"]],
    ["Gaz", ["Paliwo", "Butla", "Kuchenka", "Ciepło", "Propan"]],
    ["Gałąź", ["Drzewo", "Liście", "Natura", "Las", "Drewno"]],
    ["Guma klasyczna", ["Żucie", "Smak", "Dzieci", "Automat", "Słodkie"]],
    ["Gęś", ["Ptak", "Farma", "Dziki", "Pierze", "Jedzenie"]],
    ["Groch", ["Warzywo", "Zielony", "Strąk", "Zupa", "Nasiona"]],
    ["Gabinet", ["Pokój", "Biuro", "Praca", "Szef", "Meble"]],
    ["Garść", ["Dłoń", "Chwytanie", "Ręka", "Mało", "Ilość"]],
    ["Gramatyka", ["Język", "Zasady", "Nauka", "Słowa", "Zdania"]],
    ["Graal", ["Legenda", "Szukanie", "Rycerze", "Święty", "Kielich"]],
    ["Galeria", ["Obrazy", "Sztuka", "Miejsce", "Wystawa", "Zdjęcia"]],
    ["Grecki", ["Język", "Grecja", "Alfabet", "Starożytność", "Filozofia"]],
    ["Gród", ["Zamek", "Średniowiecze", "Mury", "Obrona", "Król"]],
    ["Gwizdek", ["Dźwięk", "Sędzia", "Gra", "Pociąg", "Sygnał"]],
    ["Gramofon", ["Muzyka", "Stary", "Płyty", "Dźwięk", "Historia"]],
    ["Guma do skakania", ["Zabawa", "Dzieci", "Skakanie", "Ulica", "Ruch"]],
    ["Gatki", ["Bielizna", "Noszenie", "Ciało", "Materiał", "Komfort"]],
    ["Gruzja", ["Kraj", "Tbilisi", "Winogrona", "Góry", "Europa"]],
    ["Grób", ["Cmentarz", "Śmierć", "Pogrzeb", "Nagrobek", "Kwiaty"]],
    ["Głuchy", ["Słuch", "Cicho", "Komunikacja", "Język migowy", "Aparat"]],
    ["Gladiator", ["Rzym", "Walka", "Koloseum", "Niewolnik", "Starożytność"]],
    ["Grochówka", ["Zupa", "Groch", "Jedzenie", "Gotowanie", "Gorące"]],
    ["Gaśnica", ["Pożar", "Bezpieczeństwo", "Ogień", "Gaszenie", "Sprzęt"]],
    ["Golarka elektryczna", ["Golenie", "Włosy", "Elektryczność", "Ostrość", "Ciało"]],
    ["Grill", ["Jedzenie", "Mięso", "Ogień", "Kiełbasa", "Letni"]],
    ["Górski", ["Góra", "Wysokość", "Wspinaczka", "Szczyt", "Turystyka"]],
    ["Golf", ["Sport", "Dołek", "Zielony", "Kij", "Piłka"]],
    ["Gofry", ["Słodkie", "Jedzenie", "Deser", "Belgijskie", "Tłuste"]],
    ["Gąsienica", ["Motyl", "Zwierzę", "Owad", "Roślina", "Metamorfoza"]],
    ["Guma do żucia", ["Żucie", "Mięta", "Zęby", "Słodkie", "Oddech"]],
    ["Gniazdo", ["Ptaki", "Drzewo", "Jaja", "Miejsce", "Domek"]],
    ["Garderoba", ["Ubrania", "Szafa", "Pokój", "Miejsce", "Hanger"]],
    ["Galareta", ["Jedzenie", "Mięso", "Deser", "Galaretka", "Tłuste"]],
    ["Gąbka", ["Myć", "Woda", "Czysty", "Kąpiel", "Morska"]],
    ["Głaz", ["Kamień", "Duży", "Ciężki", "Natura", "Geologia"]],
    ["Gryka", ["Kasza", "Jedzenie", "Zboże", "Gotowanie", "Gluten"]],
    ["Gust", ["Smak", "Jedzenie", "Podniebienie", "Odczucie", "Preferencje"]],
    ["Gabinet", ["Pokój", "Biuro", "Miejsce", "Praca", "Mebel"]],
    ["Gatunek", ["Zwierzęta", "Rośliny", "Biologia", "Klasyfikacja", "Nauka"]],
    ["Gwóźdź", ["Młotek", "Budowa", "Metal", "Ściana", "Ostrość"]],
    ["Gierka", ["Zabawa", "Gra", "Rozrywka", "Czas", "Przyjemność"]],
    ["Gotyk", ["Architektura", "Sztuka", "Średniowiecze", "Kościół", "Witraże"]],
    ["Grek", ["Narodowość", "Grecja", "Język", "Kultura", "Europa"]],
    ["Gwizdek", ["Dźwięk", "Sędzia", "Mecz", "Usta", "Sygnał"]],
    ["Gramofon", ["Muzyka", "Płyta", "Stary", "Dźwięk", "Nostalgia"]],
    ["Gwiazdozbiór", ["Gwiazda", "Noc", "Niebo", "Astronomia", "Wszechświat"]],
    ["Galop", ["Koń", "Bieg", "Szybkość", "Jazda konna", "Ruch"]],
    ["Głoska", ["Dźwięk", "Język", "Mowa", "Litera", "Słowo"]],
    ["Goniec", ["Szachy", "Gra", "Plansza", "Król", "Wieża"]],
    ["Głupota", ["Błąd", "Nieinteligencja", "Zachowanie", "Mądrość", "Myśl"]],
    ["Gryf", ["Gitara", "Muzyka", "Instrument", "Dźwięk", "Struny"]],
    ["Gawędziarz", ["Opowieść", "Rozmowa", "Historia", "Mówienie", "Słowa"]],
    ["Gwóźdź programu", ["Widowisko", "Główny", "Najważniejszy", "Pokaz", "Atrakcja"]],
    ["Gazeta", ["Czytanie", "Wiadomości", "Papier", "Druk", "Informacje"]],
    ["Gwoździec", ["Konstrukcja", "Drewno", "Budowa", "Kościół", "Architektura"]],
    ["Gąszcz", ["Las", "Rośliny", "Zarośla", "Natura", "Drzewa"]],
    ["Gniew", ["Emocja", "Złość", "Uczucie", "Reakcja", "Negatywne"]],
    ["Gorzki", ["Smak", "Czekolada", "Cytryna", "Jedzenie", "Podniebienie"]],
    ["Grot", ["Strzała", "Ostry", "Metal", "Broń", "Rzucanie"]],
    ["Gaz", ["Paliwo", "Kuchenka", "Energia", "Palnik", "Węglowodór"]],
    ["Gliceryna", ["Składnik", "Kosmetyki", "Płyn", "Lek", "Nawilżanie"]],
    ["Glukometr", ["Cukrzyca", "Zdrowie", "Pomiar", "Krew", "Choroba"]],
    ["Gnojówka", ["Ferma", "Obornik", "Zapach", "Rolnictwo", "Nawóz"]],
    ["Grzywna", ["Kara", "Pieniądze", "Prawo", "Wykroczenie", "Sąd"]],
    ["Grosz", ["Pieniądze", "Moneta", "Zakupy", "Niewiele", "Płatność"]],
    ["Gwara", ["Język", "Dialekt", "Mowa", "Region", "Słowa"]],









    ["Książka", ["Czytać", "Strona", "Okładka", "Literatura", "Rozdział"]],
    ["Słońce", ["Ciepło", "Światło", "Dzień", "Zachód", "Wschód"]],
    ["Komputer", ["Internet", "Klawiatura", "Mysz", "Monitor", "Program"]],
    ["Zegarek", ["Czas", "Wskazówka", "Godzina", "Minuta", "Sekunda"]],
    ["Drzewo", ["Liść", "Gałąź", "Korzeń", "Pień", "Owoc"]],
    ["Samochód", ["Koła", "Kierowca", "Silnik", "Siedzenie", "Droga"]],
    ["Piłka", ["Gra", "Mecz", "Bramka", "Rzut", "Boisko"]],
    ["Telefon", ["Dzwonienie", "Wiadomość", "Aplikacja", "Ekran", "Bateria"]],
    ["Muzyka", ["Piosenka", "Nota", "Dźwięk", "Instrument", "Koncert"]],
    ["Rzeka", ["Woda", "Most", "Łódź", "Prąd", "Brzeg"]],
    ["Góra", ["Wspinaczka", "Szczyt", "Rzadko", "Wysokość", "Śnieg"]],
    ["Chmura", ["Niebo", "Deszcz", "Biały", "Pogoda", "Wiatr"]],
    ["Czekolada", ["Słodki", "Deser", "Kakao", "Tabliczka", "Cukier"]],
    ["Pies", ["Szarik", "Ogon", "Szczekać", "Psiak", "Kości"]],
    ["Kwiat", ["Róża", "Płatek", "Ogrod", "Natura", "Zapach"]],
    ["Pociąg", ["Peron", "Tory", "Maszynista", "Bilet", "Podróż"]],
    ["Restauracja", ["Jedzenie", "Kelner", "Stolik", "Menu", "Rachunek"]],
    ["Telewizor", ["Obraz", "Pilot", "Kanał", "Program", "Ekran"]],
    ["Gitara", ["Struna", "Dźwięk", "Muzyk", "Piosenka", "Instrument"]],
    ["Koń", ["Gniady", "Kopyto", "Jeździć", "Siodło", "Stajnia"]],
    ["Jabłko", ["Owoc", "Drzewo", "Zielony", "Sok", "Natura"]],
    ["Czapka", ["Głowa", "Zima", "Ciepło", "Moda", "Uszy"]],
    ["Krzesło", ["Siedzenie", "Meble", "Komfort", "Drewno", "Podłoga"]],
    ["Lód", ["Zimno", "Woda", "Zima", "Kostka", "Topnieje"]],
    ["Papuga", ["Ptak", "Klatka", "Kolorowy", "Gadatliwy", "Lot"]],
    ["Deska", ["Drewno", "Materiał", "Pływak", "Surfing", "Długi"]],
    ["Malarstwo", ["Obraz", "Pędzel", "Farba", "Kolor", "Artysta"]],
    ["Pływanie", ["Basen", "Woda", "Styl", "Czas", "Trening"]],
    ["Pióro", ["Ptak", "Pisanie", "Leć", "Waga", "Kolor"]],
    ["Truskawka", ["Owoc", "Czerwony", "Lato", "Deser", "Słodki"]],
    ["Księżyc", ["Noc", "Niebo", "Satelita", "Pełnia", "Grawitacja"]],
    ["Namiot", ["Camping", "Śpiwór", "Przyroda", "Noc", "Ochrona"]],
    ["Butelka", ["Woda", "Szklany", "Napój", "Zawór", "Pojemnik"]],
    ["Wieża", ["Wysoki", "Widok", "Schody", "Architektura", "Zegar"]],
    ["Chleb", ["Pieczywo", "Żyto", "Kromka", "Bułka", "Pieczenie"]],
    ["Świeca", ["Ogień", "Światło", "Wosk", "Zapach", "Mrok"]],
    ["Rower", ["Jazda", "Koło", "Siodełko", "Kierownica", "Prędkość"]],
    ["Okulary", ["Wzrok", "Szkiełko", "Ramka", "Zobacz", "Oczy"]],
    ["Śrubokręt", ["Narzędzie", "Śruba", "Obróć", "Rękojeść", "Naprawa"]],
    ["Klawiatura", ["Komputer", "Litera", "Przycisk", "Pisanie", "Enter"]],
    ["Kamera", ["Film", "Obraz", "Nagranie", "Apertura", "Ogniskowa"]],
    ["Król", ["Korona", "Monarchia", "Królestwo", "Władca", "Zamek"]],
    ["Kolacja", ["Jedzenie", "Wieczór", "Talerz", "Napój", "Restauracja"]],
    ["Statek", ["Ocean", "Podróż", "Kapitan", "Pokład", "Żagiel"]],
    ["Pociąg", ["Peron", "Tory", "Bilet", "Podróż", "Maszynista"]],
    ["Dżungla", ["Las", "Zwierzę", "Rośliny", "Deszcz", "Dzikie"]],
    ["Zebra", ["Pas", "Przejście", "Czarny", "Biały", "Droga"]],
    ["Drewno", ["Drzewo", "Materiał", "Gałąź", "Mebel", "Deska"]],
    ["Wino", ["Alkohol", "Grono", "Butelka", "Korkociąg", "Winnica"]],
    ["Lód", ["Zimno", "Woda", "Zima", "Kostka", "Topnieje"]],
    ["Zamek", ["Król", "Budowla", "Mur", "Wieża", "Most"]],
    ["Kucharz", ["Gotować", "Kuchnia", "Przepis", "Restauracja", "Potrawa"]],
    ["Lustro", ["Odbicie", "Szklane", "Obraz", "Rama", "Ściana"]],
    ["Płaszcz", ["Zimno", "Ubranie", "Moda", "Ciepło", "Kieszeń"]],
    ["Zasłona", ["Okno", "Tkanina", "Przestrzeń", "Światło", "Intymność"]],
    ["Balerina", ["Taniec", "Balet", "Scena", "Spódnica", "Punkt"]],
    ["Pędzel", ["Malarz", "Obraz", "Kolory", "Rysunek", "Farba"]],
    ["Słoik", ["Szklany", "Pokrywka", "Przechowywanie", "Jedzenie", "Dżem"]],
    ["Dzwonek", ["Dźwięk", "Drzwi", "Wejście", "Ręka", "Klawisz"]],
    ["Księżyc", ["Noc", "Niebo", "Gwiazdy", "Satelita", "Pełnia"]],
    ["Komiks", ["Obrazki", "Bohater", "Bąbelki", "Opowieść", "Rysunek"]],
    ["Portfel", ["Pieniądze", "Kieszeń", "Skóra", "Karta", "Dokumenty"]],
    ["Biblioteka", ["Książki", "Czytanie", "Wypożyczanie", "Cisza", "Regał"]],
    ["Kaloryfer", ["Ciepło", "Zima", "Pokój", "Regulacja", "Rura"]],
    ["Latarka", ["Światło", "Ciemność", "Bateria", "Ręka", "Przenośne"]],
    ["Kaktus", ["Roślina", "Kolce", "Pustynia", "Zielony", "Doniczka"]],
    ["Kalendarz", ["Dni", "Miesiąc", "Rok", "Data", "Planowanie"]],
    ["Kołdra", ["Łóżko", "Spanie", "Ciepło", "Puch", "Poszewka"]],
    ["Skarpetki", ["Stopy", "Buty", "Bawełna", "Ciepło", "Para"]],
    ["Kubek", ["Napój", "Ucho", "Porcelana", "Ciepło", "Herbata"]],
    ["Motyl", ["Owad", "Skrzydła", "Kolor", "Lato", "Kwiat"]],
    ["Poduszka", ["Łóżko", "Głowa", "Spanie", "Miękki", "Pokrywa"]],
    ["Skarpeta", ["Stopa", "But", "Tkanina", "Ciepło", "Para"]],
    ["Kuchnia", ["Gotowanie", "Jedzenie", "Lodówka", "Piec", "Naczynia"]],
    ["Grzyb", ["Las", "Jadalny", "Kapelusz", "Trujący", "Deszcz"]],
    ["Budzik", ["Czas", "Dźwięk", "Poranek", "Spanie", "Godzina"]],
    ["Koszyk", ["Zakupy", "Rączka", "Pojemnik", "Rzeczy", "Sklep"]],
    ["Lupa", ["Powiększenie", "Szklane", "Obraz", "Szukać", "Małe"]],
    ["Wilk", ["Dziki", "Szary", "Stado", "Las", "Zęby"]],
    ["Kotwica", ["Statek", "Morze", "Mocowanie", "Ciężki", "Rzut"]],
    ["Tęcza", ["Kolory", "Deszcz", "Słońce", "Niebo", "Łuk"]],
    ["Kubek", ["Herbata", "Ucho", "Napój", "Porcelana", "Ciepło"]],
    ["Kapelusz", ["Głowa", "Słońce", "Moda", "Cień", "Rondo"]],
    ["Balon", ["Powietrze", "Lot", "Dzieci", "Kolorowy", "Urodziny"]],
    ["Chusta", ["Szyja", "Moda", "Tkanina", "Ciepło", "Zima"]],
    ["Ziemniak", ["Roślina", "Jedzenie", "Ziemne", "Gotowanie", "Frytki"]],
    ["Królik", ["Zwierzę", "Uszy", "Biały", "Marchewka", "Puść"]],
    ["Klawiatura", ["Komputer", "Pisanie", "Przycisk", "Ręka", "Litera"]]
    ];